---
- name: Remove MySQL insecure users
  sudo: yes
  mysql_user:
    state=absent
    name={{ item.user }}
    host="{{ item.host }}"
  with_items:
    - { user: "", host: "localhost" }
    - { user: "", host: "127.0.0.1" }
    - { user: "", host: "::1" }
    - { user: "", host: "{{ ansible_hostname }}" }
    - { user: "root", host: "localhost" }
    - { user: "root", host: "127.0.0.1" }
    - { user: "root", host: "::1" }
    - { user: "root", host: "{{ ansible_hostname }}" }


- name: Create MySQL users
  sudo: yes
  mysql_user:
    state=present
    name="{{ item.user }}"
    password="{{ item.password }}"
    priv="{{ item.priv | default(omit) }}"
    priv="{{ item.database | default(omit) }}.*:ALL"
    host="{{ item.host | default('localhost') }}"
  with_items: "{{ mysql_users }}"
