---
- name: Install Percona&EPEL repositories
  yum: pkg={{ item }} state=installed
  with_items:
    # https://www.percona.com/doc/percona-server/5.7/installation/yum_repo.html
    - http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    # Install EPEL reposity for "mytop" package
    - epel-release


- name: Install Percona packages
  sudo: yes
  yum: pkg={{ item }} state=present
  with_items:
    - Percona-Server-server-57
    # Python package (required for mysql_user, mysql_db)
    - MySQL-python
    - mytop


- name: Start mysql
  sudo: yes
  shell: systemctl start mysql
